---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
stringData:
  password: test
  dbname: wordpress
  dbuser: test
  dbpass: test

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
type: Opaque
stringData:
  admin_user: test
  admin_pw: test

---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secret
type: Opaque
stringData:
  INFLUXDB_DATABASE: influxdb
  INFLUXDB_USERNAME: root
  INFLUXDB_PASSWORD: root
  INFLUXDB_HOST: 192.168.99.102

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  dbname: test
  dbuser: test
  dbpass: test
  password: test

---
apiVersion: v1
kind: Secret
metadata:
  name: telegraf-secret
type: Opaque
stringData:
  INFLUXDB_DB: influxdb
  INFLUXDB_URL: http://influxdb:8086
  INFLUXDB_USER: root
  INFLUXDB_USER_PASSWORD: root
