---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: grafana
        volumeMounts:
        - mountPath: /etc/grafana/provisioning/datasources/grafana_datasource.yml
          name: grafana-config-volume
          readOnly: true
          subPath: grafana_datasource.yml
        - mountPath: /etc/grafana/provisioning/dashboards/grafana_dashboard_provider.yml
          name: grafana-config-volume
          readOnly: true
          subPath: grafana_dashboard_provider.yml
        - mountPath: /var/lib/grafana/dashboards/influxdb_dashboard.json
          name: grafana-config-volume
          readOnly: true
          subPath: influxdb_dashboard.json
        - mountPath: /var/lib/grafana/dashboards/mysql_dashboard.json
          name: grafana-config-volume
          readOnly: true
          subPath: mysql_dashboard.json
        - mountPath: /var/lib/grafana/dashboards/grafana_dashboard.json
          name: grafana-config-volume
          readOnly: true
          subPath: grafana_dashboard.json
        - mountPath: /var/lib/grafana/dashboards/nginx_dashboard.json
          name: grafana-config-volume
          readOnly: true
          subPath: nginx_dashboard.json
        - mountPath: /var/lib/grafana/dashboards/phpmyadmin_dashboard.json
          name: grafana-config-volume
          readOnly: true
          subPath: phpmyadmin_dashboard.json
        - mountPath: /var/lib/grafana/dashboards/wordpress_dashboard.json
          name: grafana-config-volume
          readOnly: true
          subPath: wordpress_dashboard.json
        - mountPath: /var/lib/grafana/dashboards/ftps_dashboard.json
          name: grafana-config-volume
          readOnly: true
          subPath: ftps_dashboard.json
        env:
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: grafana-secret
              key: admin_user
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-secret
              key: admin_pw
      volumes:
      - name: grafana-config-volume
        configMap:
          name: grafana-config
          

