
---
apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  type: LoadBalancer
  ports:
    - port: 21
      targetPort: 21
  selector:
    app: ftps

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ftps-pv-claim
  labels:
    app: ftps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      volumes:
      - name: ftps-pv-storage
        persistentVolumeClaim:
          claimName: ftps-pv-claim
      containers:
      - name: my-ftp-container
        image: fauria/vsftpd
        ports:
        - containerPort: 21
          protocol: TCP
          name: "ftp-server"
        volumeMounts:
        - mountPath: "/home/vsftpd"
          name: ftps-pv-storage
        env:
        - name: FTP_USER
          value: "root"
        - name: FTP_PASS
          value: "root"
        #- name: PASV_ADDRESS
        #  value: "127.0.0.1"
        #- name: PASV_MIN_PORT
        #  value: "21100"
        #- name: PASV_MAX_PORT
        #  value: "21110"
