---
apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  type: LoadBalancer
  ports:
    - port: 21
      targetPort: 21
      protocol: TCP
      name: ftps
    - port: 20
      targetPort: 20
      protocol: TCP
      name: active
    - port: 21000
      targetPort: 21000
      protocol: TCP
      name: passive-00
    - port: 21001
      targetPort: 21001
      protocol: TCP
      name: passive-01
    - port: 21002
      targetPort: 21002
      protocol: TCP
      name: passive-02
  selector:
    app: ftps

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: fauria/vsftpd
        ports:
        - containerPort: 21
          protocol: TCP
        - containerPort: 20
          protocol: TCP
        - containerPort: 21000
          protocol: TCP
        - containerPort: 21001
          protocol: TCP
        - containerPort: 21002
          protocol: TCP
        env:
        - name: FTP_USER
          value: "root"
        - name: FTP_PASS
          value: "root"
        - name: PASV_ADDRESS
          value: "192.168.99.201"
        - name: PASV_MIN_PORT
          value: "21000"
        - name: PASV_MAX_PORT
          value: "21002"
