---
apiVersion: v1
kind: Service
metadata: 
  name: phpmyadmin-service
  labels:
    app: phpmyadmin
spec:
  type: NodePort
  selector:
    app: phpmyadmin
  ports:
    - port: 80
      nodePort: 30090
