apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-frontend
  labels:
    app: ft-services
    type: front_end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ft-services
  template:
    metadata:
      labels:
        app: ft-services
    spec:
      containers:
      - name: ft-services
        image: nginx:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80