apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-controller
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - secretName: ingress-secret
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: nginx-frontend
          servicePort: 80
