apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  dbname: YXBwLWRi #app-db
  dbuser: YXBwLXVzZXI= #app-user
  dbpass: YXBwLXBhc3M= #app-pass
  password: YXBwLXJvb3RwYXNz #app-rootpass