# NODEPORT
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: telegraf
#   labels:
#     app: telegraf
# spec:
#   ports:
#     - port: 8125
#       nodePort: 8125
#       protocol: UDP
#   selector:
#     app: telegraf
#   type: NodePort

# CLUSTER_IP
---
apiVersion: v1
kind: Service
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  ports:
    - port: 8125
      protocol: UDP
  selector:
    app: telegraf
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: telegraf
  name: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - name: telegraf
          # image: telegraf:1.13-alpine
          image: telegraf:latest
          imagePullPolicy: Never
          envFrom:
            - secretRef:
               name: telegraf-secret
          volumeMounts:
          - name: telegraf-config-volume
            mountPath: etc/telegraf/telegraf.conf
            subPath: telegraf.conf
          - name: docker-socket
            mountPath: /var/run/docker.sock
      volumes:
      - name: telegraf-config-volume
        configMap:
          name: telegraf-config
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
