---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
  labels:
    app: telegraf
data:
  telegraf.conf: |+
    [[inputs.docker]]
      endpoint = "unix:///var/run/docker.sock"
      gather_services = false
      container_names = []
      source_tag = false
      container_name_include = []
      container_name_exclude = []
      timeout = "20s"
      perdevice = true
      total = false
      docker_label_include = []
      docker_label_exclude = []
      tag_env = ["JAVA_HOME", "HEAP_SIZE"]

    [[outputs.influxdb]]
      urls = ["$INFLUXDB_URL"]
      skip_database_creation = false
      database = "$INFLUXDB_DB"
      username = "$INFLUXDB_USER"
      password = "$INFLUXDB_USER_PASSWORD"